## Configuracion de Spring
spring:
  application:
    name: trabajo-fitting
  # Database
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/trabajo_DDBB?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA properties
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect 

## Configuracion de Instancia 
server:
  port: 8082

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: trabajo-fitting

## Configuracion secundaria (custom)
tailor:
  getOne: http://sastreria-fitting/tailor/%s